CREATE DATABASE Lession_1;
GO

USE Lession_1;
GO

CREATE TABLE STUDENT
(
    ID INT IDENTITY(1, 1),
    FULLNAME NVARCHAR(255),
    AGE INT,
)
GO

ALTER TABLE STUDENT
    ADD CONSTRAINT PK_STUDENT PRIMARY KEY(ID)
GO

ALTER TABLE STUDENT
    ADD SCHOOL NVARCHAR(255)
GO

INSERT INTO STUDENT
    (FULLNAME, AGE)
VALUES
    (N'Văn Hiền', 20),
    (N'Hồng Ngọc', 20),
    (N'Quỳnh Nga', 20);
GO

SELECT * FROM STUDENT;

SELECT * FROM STUDENT WHERE SCHOOL IS NULL;

UPDATE STUDENT SET SCHOOL = N'HUST' WHERE SCHOOL IS NULL;
